import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-electronics-component-price-variance-audit",
  "engine": "recovery",
  "title": "Electronics Component Price-Variance Audit",
  "shortTitle": "Electronics Component Price-Variance Audit",
  "tagline": "Recover component overcharges and unsupported price variances across suppliers, brokers, and contract manufacturers.",
  "industry": "Electronics Procurement Recovery",
  "buyer": "Electronics manufacturers and contract manufacturers",
  "uiPort": 4706,
  "apiPort": 5706,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Electronics Component Price-Variance Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits in one accountable workflow. Recover component overcharges and unsupported price variances across suppliers, brokers, and contract manufacturers.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Electronics Component Price-Variance Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("component-master-registry","ECP01","Component master registry","Execute component master registry using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed component master registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Component master registry Reference","text","ECP01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("approved-supplier-mapping","ECP02","Approved supplier mapping","Execute approved supplier mapping using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed approved supplier mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Approved supplier mapping Reference","text","ECP02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("quote-agreement-library","ECP03","Quote agreement library","Execute quote agreement library using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed quote agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Quote agreement library Reference","text","ECP03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("purchase-order-ingestion","ECP04","Purchase order ingestion","Execute purchase order ingestion using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed purchase order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Purchase order ingestion Reference","text","ECP04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("receipt-invoice-matching","ECP05","Receipt invoice matching","Execute receipt invoice matching using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed receipt invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Receipt invoice matching Reference","text","ECP05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("contract-price-validation","ECP06","Contract price validation","Execute contract price validation using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed contract price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Contract price validation Reference","text","ECP06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("commodity-adder-audit","ECP07","Commodity adder audit","Execute commodity adder audit using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed commodity adder audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Commodity adder audit Reference","text","ECP07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("broker-premium-review","ECP08","Broker premium review","Execute broker premium review using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed broker premium review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Broker premium review Reference","text","ECP08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("ncnr-term-validation","ECP09","NCNR term validation","Execute ncnr term validation using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed ncnr term validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","NCNR term validation Reference","text","ECP09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("moq-price-tier","ECP10","MOQ price tier","Execute moq price tier using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed moq price tier decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","MOQ price tier Reference","text","ECP10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("currency-conversion","ECP11","Currency conversion","Execute currency conversion using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed currency conversion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Currency conversion Reference","text","ECP11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("variance-calculation","ECP12","Variance calculation","Execute variance calculation using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed variance calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Variance calculation Reference","text","ECP12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("supplier-dispute-workflow","ECP13","Supplier dispute workflow","Execute supplier dispute workflow using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed supplier dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Supplier dispute workflow Reference","text","ECP13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("credit-reconciliation","ECP14","Credit reconciliation","Execute credit reconciliation using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Credit reconciliation Reference","text","ECP14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]}),
feature("part-supplier-analytics","ECP15","Part supplier analytics","Execute part supplier analytics using purchase agreements, approved vendor lists, component parts, quotes, purchase orders, receipts, invoices, commodity adjustments, NCNR terms, and credits.","Produce a governed part supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Component Part","text","Supplier / Component Part · Standard Case"],["caseReference","Part supplier analytics Reference","text","ECP15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1373750],["supportedAmount","Evidence-Supported Amount","currency",1153950],["domainDriver","Variance Driver","select","Contract price",["Contract price","Commodity adder","NCNR condition"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Component master registry case","Approved supplier mapping case","Quote agreement library case","Purchase order ingestion case","Receipt invoice matching case"]})
]);
